### PR TITLE
issue solved

### PR DESCRIPTION
**Pull request by cragia**
To solve the issue I was talking about I added a function that searches the country with an exact match of the value passed in.

### CODE REVIEW

**Comment by cragia** [comment]
hello again.
have you had the chance to look at this changes? if there's something you need me to change, just tell me, and I'll do it.

thank you.

**Comment by ersel** [comment]
Hi Cragia, 

Sorry really busy with work this week. I'll make some time tomorrow or Saturday to check it.

Could you update the readme file to showcase the `findCountryExact` method  please?

**Comment by cragia** [comment]
ok done!
Thank you for your time! :)

**Comment by ersel** [comment]
No problem. Thanks for your contribution @cragia !

**Comment by cragia** [comment]
Hi again ersel!
Sorry to be annoying, did you have a chance to look at this pull request? I would like to port this package into production...

thank you.

**Comment by ersel** [comment]
Hi Cragia,

Sorry for taking so long. I've merged this PR in now. Thanks for your contribution 🙏 

I did a slight refactor of the functionality, so instead of creating a new function `findCountryExact` you can achieve this behaviour by passing an optional boolean argument to `findCountry` function instead.

```
let uk = CountryCodes.findCountry({'ds': 'gb'}, true); // exact match
```

Hope this helps!

All the best,
E

**Pull request merged**
